- name: variables
  hosts: frontend
  connection: local
  vars:
    COURSE: ansible
    TRAINER: siva
    DURATION: 10H

  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{COURSE}}, course duration {{DURATION}}, trainer is {{TRAINER}}"
    